### PR TITLE
Source map support for js

### PR DESCRIPTION
**Pull request by kolesnikovde**
What's included:

- line-to-line mapping for includes,
- input source map support (i.e. from `//# sourceMappingURL=` or `.map` files),
- `uglify-es` support,
- works well with `inputString`,
- backward compatible.

### CODE REVIEW

**Comment by miripiruni** [comment]
LGTM!

**Comment by tadatuta** [comment]
@miripiruni @kolesnikovde 
Is it ready? I'm fine to merge.
Do we need a minor release when it's merged?

**Comment by miripiruni** [comment]
@tadatuta Until we are finished fiji patching I'd better not to release it. But we can release RC.

**Comment by miripiruni** [comment]
Let’s release v2.1.0-rc

**Pull request merged**
